# Generated by Django 5.0.7 on 2024-08-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
                ('customer_name', models.CharField(db_comment='do not edit', max_length=128)),
                ('legal_entity_name', models.CharField(db_comment='do not edit', max_length=128)),
                ('business_tax_number', models.CharField(blank=True, db_comment='do not edit', max_length=128, null=True)),
                ('delivery_address', models.CharField(db_comment='do not edit', max_length=255)),
                ('active', models.CharField(db_comment='Yes or No', max_length=3)),
                ('customer_code', models.CharField(max_length=255, unique=True)),
                ('allow_duplicate_customer_code', models.CharField(db_comment='Yes or No', max_length=3)),
                ('pricing_level', models.CharField(blank=True, max_length=255, null=True)),
                ('negotiated_prices_group', models.CharField(blank=True, max_length=255, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('show_only_negotiated_pricing', models.CharField(db_comment='Yes or No', max_length=3)),
                ('show_rrp', models.CharField(db_comment='Yes or No', max_length=3)),
                ('delivery_run_code', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_run_position', models.IntegerField(blank=True, null=True)),
                ('delivery_days_and_cut_off_times_group', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_term_days', models.IntegerField(blank=True, null=True)),
                ('payment_term_option', models.CharField(blank=True, max_length=255, null=True)),
                ('charge_card', models.CharField(db_comment='Yes or No', max_length=3)),
                ('charge_customer_card_fee', models.CharField(db_comment='Yes or No', max_length=3)),
                ('freight_rule', models.CharField(blank=True, max_length=255, null=True)),
                ('minimum_order_amount_for_freight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('delivery_date_message', models.CharField(blank=True, max_length=255, null=True)),
                ('standing_delivery_instructions', models.CharField(blank=True, max_length=255, null=True)),
                ('standing_picking_instructions', models.CharField(blank=True, max_length=255, null=True)),
                ('internal_customer_contact_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('internal_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('visibility_groups', models.CharField(db_comment='do not edit', max_length=255)),
                ('agreement_id', models.CharField(db_comment='do not edit', max_length=36)),
                ('sales_person', models.CharField(blank=True, db_comment="who's customer", max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, db_comment='UTC', null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_comment='UTC', null=True)),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
    ]
