# Generated by Django 5.0.7 on 2024-08-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
                ('order_number', models.CharField(max_length=255, unique=True)),
                ('delivery_date', models.DateField()),
                ('receiving_company_id', models.CharField(max_length=36)),
                ('receiving_company_name', models.CharField(max_length=255)),
                ('additional_notes', models.CharField(blank=True, max_length=4000, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_address', models.CharField(max_length=255)),
                ('delivery_method', models.CharField(max_length=255)),
                ('delivery_venue', models.CharField(max_length=255)),
                ('external_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_instructions', models.CharField(blank=True, max_length=255, null=True)),
                ('prefixed_order_number', models.CharField(max_length=255)),
                ('formatted_cached_payable_total', models.CharField(max_length=255)),
                ('payable_total_in_cents', models.IntegerField(db_comment='total in cents', default=0)),
                ('submitted_at', models.DateTimeField(blank=True, db_comment='UTC', null=True)),
                ('state', models.CharField(max_length=255)),
                ('placed_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_run', models.CharField(blank=True, max_length=255, null=True)),
                ('products', models.JSONField(blank=True, null=True)),
                ('delivery_at', models.DateTimeField(blank=True, db_comment='UTC', null=True)),
                ('delivery_by', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_proof_url', models.CharField(blank=True, max_length=255, null=True)),
                ('locked', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, db_comment='UTC', null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_comment='UTC', null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
    ]
