# Generated by Django 5.0.7 on 2024-08-11 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'managed': True},
        ),
    ]
