# Generated by Django 5.0.7 on 2024-08-14 12:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(blank=True, db_comment='UTC', null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_comment='UTC', null=True)),
            ],
        ),
    ]
