# Generated by Django 5.0.7 on 2024-08-14 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_deliveryrun'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryrun',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='deliveryrun',
            table='runs',
        ),
    ]
