# Generated by Django 5.0.7 on 2024-08-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_created_at_alter_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_proof',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
